export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'

export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'

export const PRODUCT_VARIATION_FETCH_START = 'PRODUCT_VARIATION_FETCH_START'
export const PRODUCT_VARIATION_FETCH_SUCCESS = 'PRODUCT_VARIATION_FETCH_SUCCESS'
export const PRODUCT_VARIATION_FETCH_FAIL = 'PRODUCT_VARIATION_FETCH_FAIL'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const PROFILE_FETCH_START = 'PROFILE_FETCH_START'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'

export const ADDRESS_FETCH_START = 'ADDRESS_FETCH_START'
export const ADDRESS_FETCH_FAIL = 'ADDRESS_FETCH_FAIL'
export const ADDRESS_FETCH_SUCCESS = 'ADDRESS_FETCH_SUCCESS'

export const CUSTOMER_FETCH_START = 'CUSTOMER_FETCH_START'
export const CUSTOMER_FETCH_FAIL = 'CUSTOMER_FETCH_FAIL'
export const CUSTOMER_FETCH_SUCCESS = 'CUSTOMER_FETCH_SUCCESS'

export const SELLER_FETCH_START = 'SELLER_FETCH_START'
export const SELLER_FETCH_FAIL = 'SELLER_FETCH_FAIL'
export const SELLER_FETCH_SUCCESS = 'SELLER_FETCH_SUCCESS'

export const METADATA_FIELD_POST_START = 'METADATA_FIELD_POST_START'
export const METADATA_FIELD_POST_FAIL = 'METADATA_FIELD_POST_FAIL'
export const METADATA_FIELD_POST_SUCCESS = 'METADATA_FIELD_POST_SUCCESS'

export const METADATA_FIELD_VALUE_POST_START = 'METADATA_FIELD_POST_START'
export const METADATA_FIELD_VALUE_POST_FAIL = 'METADATA_FIELD_POST_FAIL'
export const METADATA_FIELD_VALUE_POST_SUCCESS = 'METADATA_FIELD_POST_SUCCESS'

export const METADATA_FIELD_FETCH_START = 'METADATA_FIELD_FETCH_START'
export const METADATA_FIELD_FETCH_FAIL = 'METADATA_FIELD_FETCH_FAIL'
export const METADATA_FIELD_FETCH_SUCCESS = 'METADATA_FIELD_FETCH_SUCCESS'

export const CATEGORY_POST_START = 'CATEGORY_POST_START'
export const CATEGORY_POST_FAIL = 'CATEGORY_POST_FAIL'
export const CATEGORY_POST_SUCCESS = 'CATEGORY_POST_SUCCESS'

export const CATEGORY_FETCH_START = 'CATEGORY_FETCH_START'
export const CATEGORY_FETCH_FAIL = 'CATEGORY_FETCH_FAIL'
export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS'
