export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'

export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START'
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL = 'PRODUCT_FETCH_FAIL'

export const PRODUCT_VARIATION_FETCH_START = 'PRODUCT_VARIATION_FETCH_START'
export const PRODUCT_VARIATION_FETCH_SUCCESS = 'PRODUCT_VARIATION_FETCH_SUCCESS'
export const PRODUCT_VARIATION_FETCH_FAIL = 'PRODUCT_VARIATION_FETCH_FAIL'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const PROFILE_FETCH_START = 'PROFILE_FETCH_START'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'

export const ADDRESS_FETCH_START = 'ADDRESS_FETCH_START'
export const ADDRESS_FETCH_FAIL = 'ADDRESS_FETCH_FAIL'
export const ADDRESS_FETCH_SUCCESS = 'ADDRESS_FETCH_SUCCESS'